/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.beans.PropertyVetoException;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author usaid
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuItemCustomer = new javax.swing.JMenuItem();
        menuItemSupplier = new javax.swing.JMenuItem();
        menuItemPegawai = new javax.swing.JMenuItem();
        menuItemUser = new javax.swing.JMenuItem();
        menuItemLogout = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuItemBarang = new javax.swing.JMenuItem();
        menuItemSatuanBeli = new javax.swing.JMenuItem();
        menuItemSatuanJual = new javax.swing.JMenuItem();
        menuItemKategori = new javax.swing.JMenuItem();
        menuItemJabatan = new javax.swing.JMenuItem();
        menuItemGroup = new javax.swing.JMenuItem();
        menuItemHakAkses = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuItemTransaksiPembelian = new javax.swing.JMenuItem();
        menuItemTransaksiPenjualan = new javax.swing.JMenuItem();
        menuItemTransaksiReturnPembelian = new javax.swing.JMenuItem();
        menuItemTransaksiReturnPenjualan = new javax.swing.JMenuItem();
        menuItemTransaksiHutang = new javax.swing.JMenuItem();
        menuItemTransaksiPiutang = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLaporanPembelian = new javax.swing.JMenuItem();
        menuLaporanPenjualan = new javax.swing.JMenuItem();
        menuLaporanReturnPembelian = new javax.swing.JMenuItem();
        menuLaporanReturnPenjualan = new javax.swing.JMenuItem();
        menuLaporanHutang = new javax.swing.JMenuItem();
        menuLaporanPiutang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        menuFile.setText("File");

        menuItemCustomer.setText("Customer");
        menuFile.add(menuItemCustomer);

        menuItemSupplier.setText("Supplier");
        menuFile.add(menuItemSupplier);

        menuItemPegawai.setText("Pegawai");
        menuFile.add(menuItemPegawai);

        menuItemUser.setText("User");
        menuFile.add(menuItemUser);

        menuItemLogout.setText("Logout");
        menuFile.add(menuItemLogout);

        jMenuBar1.add(menuFile);

        menuMaster.setText("Master");

        menuItemBarang.setText("Barang");
        menuMaster.add(menuItemBarang);

        menuItemSatuanBeli.setText("Satuan Beli");
        menuItemSatuanBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSatuanBeliActionPerformed(evt);
            }
        });
        menuMaster.add(menuItemSatuanBeli);

        menuItemSatuanJual.setText("Satuan Jual");
        menuItemSatuanJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSatuanJualActionPerformed(evt);
            }
        });
        menuMaster.add(menuItemSatuanJual);

        menuItemKategori.setText("Kategori");
        menuItemKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemKategoriActionPerformed(evt);
            }
        });
        menuMaster.add(menuItemKategori);

        menuItemJabatan.setText("Jabatan");
        menuMaster.add(menuItemJabatan);

        menuItemGroup.setText("Group User");
        menuMaster.add(menuItemGroup);

        menuItemHakAkses.setText("Hak Akses Group");
        menuMaster.add(menuItemHakAkses);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaksi");

        menuItemTransaksiPembelian.setText("Pembelian");
        menuTransaksi.add(menuItemTransaksiPembelian);

        menuItemTransaksiPenjualan.setText("Penjualan");
        menuTransaksi.add(menuItemTransaksiPenjualan);

        menuItemTransaksiReturnPembelian.setText("Return Pembelian");
        menuTransaksi.add(menuItemTransaksiReturnPembelian);

        menuItemTransaksiReturnPenjualan.setText("Return Penjualan");
        menuTransaksi.add(menuItemTransaksiReturnPenjualan);

        menuItemTransaksiHutang.setText("Hutang");
        menuTransaksi.add(menuItemTransaksiHutang);

        menuItemTransaksiPiutang.setText("Piutang");
        menuTransaksi.add(menuItemTransaksiPiutang);

        jMenuBar1.add(menuTransaksi);

        menuLaporan.setText("Laporan");

        menuLaporanPembelian.setText("Pembelian");
        menuLaporan.add(menuLaporanPembelian);

        menuLaporanPenjualan.setText("Penjualan");
        menuLaporan.add(menuLaporanPenjualan);

        menuLaporanReturnPembelian.setText("Pembelian");
        menuLaporan.add(menuLaporanReturnPembelian);

        menuLaporanReturnPenjualan.setText("Penjualan");
        menuLaporan.add(menuLaporanReturnPenjualan);

        menuLaporanHutang.setText("Hutang");
        menuLaporan.add(menuLaporanHutang);

        menuLaporanPiutang.setText("Piutang");
        menuLaporan.add(menuLaporanPiutang);

        jMenuBar1.add(menuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemSatuanBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSatuanBeliActionPerformed
        // TODO add your handling code here:
        try{  
            boolean status=false;  
            javax.swing.JInternalFrame[] children;  
            children=DesktopPane.getAllFrames();  
            for (JInternalFrame f:children){  
              if(f.getTitle().equals("Form Satuan Beli")){  
                f.setSelected(true);  
                status=true;  
                break;  
              }  
            }  
            if (status==false){  
              View.FormSatuanBeli form = new View.FormSatuanBeli();
              DesktopPane.add(form);  
              form.setVisible(true);  
            }  
          }  
          catch(PropertyVetoException e){  
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error",  JOptionPane.ERROR_MESSAGE);  
          }
        
    }//GEN-LAST:event_menuItemSatuanBeliActionPerformed

    private void menuItemSatuanJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSatuanJualActionPerformed
        // TODO add your handling code here:
        try{  
            boolean status=false;  
            javax.swing.JInternalFrame[] children;  
            children=DesktopPane.getAllFrames();  
            for (JInternalFrame f:children){  
              if(f.getTitle().equals("Form Satuan Jual")){  
                f.setSelected(true);  
                status=true;  
                break;  
              }  
            }  
            if (status==false){  
              View.FormSatuanJual form = new View.FormSatuanJual();
              DesktopPane.add(form);  
              form.setVisible(true);  
            }  
          }  
          catch(PropertyVetoException e){  
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error",  JOptionPane.ERROR_MESSAGE);  
          }
    }//GEN-LAST:event_menuItemSatuanJualActionPerformed

    private void menuItemKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Form().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuItemBarang;
    private javax.swing.JMenuItem menuItemCustomer;
    private javax.swing.JMenuItem menuItemGroup;
    private javax.swing.JMenuItem menuItemHakAkses;
    private javax.swing.JMenuItem menuItemJabatan;
    private javax.swing.JMenuItem menuItemKategori;
    private javax.swing.JMenuItem menuItemLogout;
    private javax.swing.JMenuItem menuItemPegawai;
    private javax.swing.JMenuItem menuItemSatuanBeli;
    private javax.swing.JMenuItem menuItemSatuanJual;
    private javax.swing.JMenuItem menuItemSupplier;
    private javax.swing.JMenuItem menuItemTransaksiHutang;
    private javax.swing.JMenuItem menuItemTransaksiPembelian;
    private javax.swing.JMenuItem menuItemTransaksiPenjualan;
    private javax.swing.JMenuItem menuItemTransaksiPiutang;
    private javax.swing.JMenuItem menuItemTransaksiReturnPembelian;
    private javax.swing.JMenuItem menuItemTransaksiReturnPenjualan;
    private javax.swing.JMenuItem menuItemUser;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLaporanHutang;
    private javax.swing.JMenuItem menuLaporanPembelian;
    private javax.swing.JMenuItem menuLaporanPenjualan;
    private javax.swing.JMenuItem menuLaporanPiutang;
    private javax.swing.JMenuItem menuLaporanReturnPembelian;
    private javax.swing.JMenuItem menuLaporanReturnPenjualan;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
